# Generated by Django 5.1.1 on 2024-10-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="tasks",
        ),
    ]
